# Generated by Django 3.0.7 on 2021-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20210629_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url_name',
            field=models.SlugField(unique=True),
        ),
    ]
